# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftag_types.proto\x12\ttag_types\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xd8\x01\n\nTagMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12\x0c\n\x04slug\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ndeleted_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1f\n\rGetTagRequest\x12\x0e\n\x06obj_id\x18\x01 \x01(\x05\"H\n\x16\x43reateUpdateTagRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tis_active\x18\x02 \x01(\x08\x12\x0c\n\x04slug\x18\x03 \x01(\t\"Y\n\x0fListTagsRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x10\n\x08order_by\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x04 \x01(\x08\"|\n\x10UpdateTagRequest\x12\x0e\n\x06obj_id\x18\x01 \x01(\x03\x12.\n\x03tag\x18\x02 \x01(\x0b\x32!.tag_types.CreateUpdateTagRequest\x12(\n\x04mask\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"\x8c\x01\n\x10ListTagsResponse\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x11\n\tnum_pages\x18\x03 \x01(\x05\x12\x15\n\rtotal_results\x18\x04 \x01(\x05\x12&\n\x07results\x18\x05 \x03(\x0b\x32\x15.tag_types.TagMessage\"\"\n\x10\x44\x65leteTagRequest\x12\x0e\n\x06obj_id\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAGMESSAGE._serialized_start=98
  _TAGMESSAGE._serialized_end=314
  _GETTAGREQUEST._serialized_start=316
  _GETTAGREQUEST._serialized_end=347
  _CREATEUPDATETAGREQUEST._serialized_start=349
  _CREATEUPDATETAGREQUEST._serialized_end=421
  _LISTTAGSREQUEST._serialized_start=423
  _LISTTAGSREQUEST._serialized_end=512
  _UPDATETAGREQUEST._serialized_start=514
  _UPDATETAGREQUEST._serialized_end=638
  _LISTTAGSRESPONSE._serialized_start=641
  _LISTTAGSRESPONSE._serialized_end=781
  _DELETETAGREQUEST._serialized_start=783
  _DELETETAGREQUEST._serialized_end=817
# @@protoc_insertion_point(module_scope)
